### ISSUE TITLE
As a user I want to find Neatline after it's installed

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/neatline-omeka-s#60]
There is currently no way to find neatline apart from appending `/s/neatline` to the URL.

**Comment by jamiefolsom** [comment]
Fullscreen mode too, per: #66 @akstuhl

**Comment by akstuhl** [comment]
Implementation notes -- in order to reproduce how Neatline is made visible to users and admins in Omeka Classic, adding this feature will involve two parts:

1) **Admin-facing link in dashboard menu:** as an Omeka S admin, once I have installed the Neatline module and created a Site within my Omeka S instance, I should see a "Neatline" row in the dashboard sub-menu for that Site that appears when I click "Sites" in the top-level dashboard menu and then click the name of the Site (the Neatline row should appear in this sub-menu rather than at the top level because Neatline exhibits will be scoped to Sites, allowing different Site admins within an instance to manage their own Neatline exhibit collections). This Neatline link in the dashboard sub-menu should point to the Neatline exhibit table view at site-public-url/neatline, from which the admin will be able to open any exhibit for editing.
2) **Entry in Site navigation settings:** modeling how Neatline for Omeka Classic makes itself visible by default to public users, installing Neatline should add an entry in the navigation list for each Site in the Omeka S instance. This entry should be point to site-public-url/neatline and should have the label "Neatline", which Site admins can edit or turn off later. Any new Site created once the Neatline module has been installed should likewise receive this entry in its navigation list.
