### ISSUE TITLE
Add settings option for individual exhibit themes

### ISSUE THREAD

**Issue by eam5** [performant-software/neatline-omeka-s#69]
Option in exhibit settings for users to set a theme for individual Neatline exhibits, separate from their main Omeka theme. See Exhibit Builder plugin as an example: https://github.com/omeka/plugin-ExhibitBuilder/blob/master/functions.php#L504-L528

Would require exhibit settings to exist in Omeka admin interface?

**Comment by jamiefolsom** [comment]
Hi @eam5 -- In _this_ version of neatline, pretty much all settings for exhibits are intended to be managed by, and through, the [SPA](https://github.com/scholarslab/neatline-spa). That said, theming in particular is a bit of a tricky case, since Neatline as a whole has a theme of sorts, as distinct from the Omeka theme that's in play. Regardless, good question, and worth discussing. I've assigned this to myself and @akstuhl as well. Thanks!

**Comment by eam5** [comment]
Not relevant for updated versions of Omeka S 2.0+, page blocks replaced exhibit builder
